#!/bin/sh

blockMesh

# delete if exist
rm -r system/refineMeshDict

# c0
topoSet
cp -a system/refineMeshDict0 system/refineMeshDict
refineMesh -overwrite
rm -r system/refineMeshDict

# c1
topoSet
cp -a system/refineMeshDict1 system/refineMeshDict
refineMesh -overwrite
rm -r system/refineMeshDict

#------------------------------------------------------------------------------
