#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

./Allrun.pre

cd background 

renumberMesh -overwrite

# run in serial mode
runApplication $(getApplication)

# run in parallel mode
#runApplication decomposePar -cellDist
#runParallel  $(getApplication)

#------------------------------------------------------------------------------
