#!/bin/sh
#cd ${0%/*} || exit 1                        # Run from this directory
#. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

blockMesh

# delete if exist
rm -r system/topoSetDict
rm -r system/refineMeshDict

# first level refinement
echo "First level refinement..."
echo "  Refining cells near the free surface..."
cp -a system/topoSetDict1 system/topoSetDict
# c0
topoSet > toposet_level1.log
cp -a system/refineMeshDict0 system/refineMeshDict
refineMesh -overwrite > refine_level1_c0.log
rm -r system/refineMeshDict

echo "  Refining cells near the source..."
# c1
topoSet > toposet_level1.log
cp -a system/refineMeshDict1 system/refineMeshDict
refineMesh -overwrite > refine_level1_c1.log
rm -r system/refineMeshDict

echo "  Refining cells near the structure..."
# c2
topoSet > toposet_level1.log
cp -a system/refineMeshDict2 system/refineMeshDict
refineMesh -overwrite > refine_level1_c2.log
rm -r system/refineMeshDict

# delete
rm -r system/topoSetDict
cp -a system/topoSetDict2 system/topoSetDict

# second level refinement
echo "Second level refinement..."
echo "  Refining cells near the free surface..."
# c0
topoSet > toposet_level2.log
cp -a system/refineMeshDict0 system/refineMeshDict
refineMesh -overwrite > refine_level2_c0.log
rm -r system/refineMeshDict

echo "  Refining cells near the source..."
# c1
topoSet > toposet_level2.log
cp -a system/refineMeshDict1 system/refineMeshDict
refineMesh -overwrite > refine_level2_c1.log
rm -r system/refineMeshDict

echo "  Refining cells near the structure..."
# c2
topoSet > toposet_level2.log
cp -a system/refineMeshDict2 system/refineMeshDict
refineMesh -overwrite > refine_level2_c2.log
rm -r system/refineMeshDict

# additional refinement (x-only)
# c3
topoSet > toposet_level3.log
cp -a system/refineMeshDict3 system/refineMeshDict
refineMesh -overwrite > refine_level3_c3.log
rm -r system/refineMeshDict

echo "Snappy for the structure..."
# perforated wall
snappyHexMesh -overwrite > log.SHM

rm -r system/topoSetDict
cp -a system/topoSetDictA system/topoSetDict

#------------------------------------------------------------------------------
